### ISSUE TITLE
How to get user input when it run?

### ISSUE THREAD

**Issue by LONGDDSF** [CocoaPods/CLAide#91]
I am making a command from the CLAide.
This is my code:
```
      def run
          puts "please input your name："
          userInput = gets.chomp.delete(' ')
          puts userInput
      end
```
but ,I got an error.
```
please input your name：
bundler: failed to load command: bin/dj (bin/dj)
Errno::ENOENT: No such file or directory @ rb_sysopen - code
  /Users/cw/Documents/Dy/tools/DYAutomate/lib/DYAutomate/Command/codeGenerate.rb:43:in `gets'
  /Users/cw/Documents/Dy/tools/DYAutomate/lib/DYAutomate/Command/codeGenerate.rb:43:in `gets'
  /Users/cw/Documents/Dy/tools/DYAutomate/lib/DYAutomate/Command/codeGenerate.rb:43:in `block in run'
  /Users/cw/Documents/Dy/tools/DYAutomate/lib/DYAutomate/Command/codeGenerate.rb:43:in `noecho'
  /Users/cw/Documents/Dy/tools/DYAutomate/lib/DYAutomate/Command/codeGenerate.rb:43:in `run'
  /Users/cw/.rvm/gems/ruby-2.4.1/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  bin/dj:5:in `<top (required)>'

```
How can I do it?

**Comment by LONGDDSF** [comment]
I want to implement a feature ,the human-computer interaction.
